[package]
name = "to_app_inventor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# rstsc = { path = "../../../../rstsc/rstsc" }
wasm-bindgen = "0.2.92"

