import { instructions } from "./ins.ts"

const indent = "\t"

const insToVal = "\nexport const Ins = {\n" + (instructions
	.map((e, i) => indent + `${e}: ${i} as const`)
	.join(",\n")) + "\n}\n"

const valToIns = "\nexport const BackwardIns = {\n" + (instructions
	.map((e, i) => indent + `${i}: '${e}' as const`)
	.join(",\n")) + "\n}\n"

Deno.writeTextFileSync("src/ins.ts", `\
// This code was generated by \`ins/gen.ts\`
${insToVal}
${valToIns}
`)
